import GhostAdminAPI from "@tryghost/admin-api";
import type { CompanyInsight } from "../types";

export interface PublishResult {
  url: string;
  publishedAt: string;
  external: boolean; // true when published to real Ghost; false when using local /report fallback
}

// Ghost publishing adapter.
// Uses ghost_admin_api + ghost_url if present → real post on Ghost blog.
// Otherwise returns the local /report/[id] URL so the app keeps working.

interface AdminClient {
  posts: {
    add: (
      post: { title: string; html: string; status: string; tags?: Array<{ name: string }> },
      options: { source: "html" },
    ) => Promise<{ url: string; id: string }>;
  };
}

let client: AdminClient | null = null;

function getClient(): AdminClient | null {
  if (client) return client;
  const key = process.env.ghost_admin_api;
  const url = process.env.ghost_url;
  if (!key || !url) return null;
  client = new GhostAdminAPI({ url, key, version: "v5.0" }) as unknown as AdminClient;
  return client;
}

export async function publish(insight: CompanyInsight, origin: string): Promise<PublishResult> {
  const admin = getClient();
  const embedOrigin = process.env.APP_PUBLIC_URL || origin;

  if (!admin) {
    return {
      url: `${origin}/report/${insight.id}`,
      publishedAt: new Date().toISOString(),
      external: false,
    };
  }

  const html = renderPostHtml(insight, embedOrigin);
  const title = `${insight.name} — Intelligence Report`;
  try {
    const post = await admin.posts.add(
      { title, html, status: "published", tags: [{ name: "SuperBrain" }, { name: insight.name }] },
      { source: "html" },
    );
    return { url: post.url, publishedAt: new Date().toISOString(), external: true };
  } catch (err) {
    console.error("[ghost] publish failed, falling back to /report:", err);
    return {
      url: `${origin}/report/${insight.id}`,
      publishedAt: new Date().toISOString(),
      external: false,
    };
  }
}

function renderPostHtml(insight: CompanyInsight, embedOrigin: string): string {
  const stats = `
    <ul>
      <li><strong>Headcount:</strong> ${insight.employeeTrend.headcount}</li>
      <li><strong>30-day growth:</strong> ${(insight.employeeTrend.growth30d * 100).toFixed(1)}%
        (${insight.employeeTrend.signal})</li>
      <li><strong>Public sentiment:</strong> ${insight.publicSentiment.score.toFixed(2)}
        (${insight.publicSentiment.trend})</li>
    </ul>`;

  const claims = insight.officialClaims.map((c) => `<li>${escapeHtml(c)}</li>`).join("");
  const competitors = insight.competitors
    .map((c) => `<li><strong>${escapeHtml(c.name)}</strong> — ${escapeHtml(c.overlap)} (${Math.round(c.strength * 100)}%)</li>`)
    .join("");
  const people = insight.keyPeople
    .map((p) => `<li><strong>${escapeHtml(p.name)}</strong> — ${escapeHtml(p.role)}</li>`)
    .join("");
  const sources = insight.sources
    .map((s) => `<li><a href="${s.url}">[${s.kind}] ${escapeHtml(s.title)}</a></li>`)
    .join("");
  const contradictions = insight.contradictions.length
    ? `<h3>Contradictions</h3><ul>${insight.contradictions
        .map(
          (c) =>
            `<li><strong>${escapeHtml(c.claim)}</strong> — counter: <a href="${c.counterSource}">${c.counterSource}</a><br><em>${escapeHtml(c.counterEvidence)}</em></li>`,
        )
        .join("")}</ul>`
    : "";

  return `
    <p>${escapeHtml(insight.summary)}</p>
    ${stats}
    <h3>3D Knowledge Map</h3>
    <figure>
      <iframe src="${embedOrigin}/embed/map/${insight.id}"
              width="100%" height="520" frameborder="0" allowfullscreen
              style="border:0;border-radius:8px;background:#07080a"></iframe>
      <figcaption>Drag to rotate · scroll to zoom · live from SuperBrain</figcaption>
    </figure>
    <h3>Official claims</h3>
    <ul>${claims}</ul>
    <h3>Key people</h3>
    <ul>${people}</ul>
    <h3>Competitors</h3>
    <ul>${competitors}</ul>
    ${contradictions}
    <h3>Sources</h3>
    <ul>${sources}</ul>
    <hr>
    <p><em>Generated by SuperBrain · ${insight.generatedAt}</em></p>
  `.trim();
}

function escapeHtml(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");
}
