import GhostAdminAPI from "@tryghost/admin-api";
import type { CompanyInsight } from "../types";

export interface PublishResult {
  url: string;
  publishedAt: string;
  external: boolean; // true when published to real Ghost; false when using local /report fallback
}

// Ghost publishing adapter.
// Uses ghost_admin_api + ghost_url if present → real post on Ghost blog.
// Otherwise returns the local /report/[id] URL so the app keeps working.

interface AdminClient {
  posts: {
    add: (
      post: { title: string; html: string; status: string; tags?: Array<{ name: string }> },
      options: { source: "html" },
    ) => Promise<{ url: string; id: string }>;
  };
}

let client: AdminClient | null = null;

function getClient(): AdminClient | null {
  if (client) return client;
  const key = process.env.ghost_admin_api;
  const url = process.env.ghost_url;
  if (!key || !url) return null;
  client = new GhostAdminAPI({ url, key, version: "v5.0" }) as unknown as AdminClient;
  return client;
}

export async function publish(insight: CompanyInsight, origin: string): Promise<PublishResult> {
  const admin = getClient();
  const embedOrigin = process.env.APP_PUBLIC_URL || origin;

  if (!admin) {
    return {
      url: `${origin}/report/${insight.id}`,
      publishedAt: new Date().toISOString(),
      external: false,
    };
  }

  const html = renderPostHtml(insight, embedOrigin);
  const title = `${insight.name} — Intelligence Report`;
  try {
    const post = await admin.posts.add(
      { title, html, status: "published", tags: [{ name: "SuperBrain" }, { name: insight.name }] },
      { source: "html" },
    );
    return { url: post.url, publishedAt: new Date().toISOString(), external: true };
  } catch (err) {
    console.error("[ghost] publish failed, falling back to /report:", err);
    return {
      url: `${origin}/report/${insight.id}`,
      publishedAt: new Date().toISOString(),
      external: false,
    };
  }
}

function renderPostHtml(insight: CompanyInsight, embedOrigin: string): string {
  // Ghost post = free tier only. This is the public, distribution-facing
  // version — summary, stats, 3D map, a couple of official claims, and a
  // prominent CTA driving readers to the paywalled deep-research view on
  // our own domain. Paywalled content (contradictions, full people list,
  // full competitors, full sources) lives only on /report/[id] behind the
  // x402 unlock — we do NOT leak it into Ghost.

  const stats = `
    <ul>
      <li><strong>Headcount:</strong> ${insight.employeeTrend.headcount}</li>
      <li><strong>30-day growth:</strong> ${(insight.employeeTrend.growth30d * 100).toFixed(1)}%
        (${insight.employeeTrend.signal})</li>
      <li><strong>Public sentiment:</strong> ${insight.publicSentiment.score.toFixed(2)}
        (${insight.publicSentiment.trend})</li>
    </ul>`;

  // Show at most 2 claims as a teaser; the rest stays gated.
  const claims = insight.officialClaims
    .slice(0, 2)
    .map((c) => `<li>${escapeHtml(c)}</li>`)
    .join("");

  // Teaser counts — prove the depth exists without giving it away.
  const deepStats = `
    <ul>
      <li><strong>${insight.contradictions.length}</strong> contradictions surfaced between official claims and public signal</li>
      <li><strong>${insight.keyPeople.length}</strong> key people identified with roles</li>
      <li><strong>${insight.competitors.length}</strong> competitors with overlap scoring</li>
      <li><strong>${insight.sources.length}</strong> cited sources</li>
    </ul>`;

  const cta = `
    <figure style="margin:2rem 0;padding:1.5rem;border-radius:12px;background:linear-gradient(135deg,rgba(0,240,255,0.08),rgba(182,0,248,0.10));border:1px solid rgba(0,240,255,0.25);text-align:center">
      <p style="margin:0 0 .5rem;font-size:14px;letter-spacing:.15em;text-transform:uppercase;color:#00f0ff">Deep research · 1 USDC via x402</p>
      <p style="margin:0 0 1rem;font-size:16px">
        Unlock contradictions, full people list, competitor matrix, and the complete source bibliography.
      </p>
      <a href="${embedOrigin}/report/${insight.id}"
         style="display:inline-block;padding:.75rem 1.5rem;border-radius:999px;background:linear-gradient(135deg,#00f0ff,#b600f8);color:#05141c;text-decoration:none;font-weight:600">
        Open full report →
      </a>
    </figure>`;

  return `
    <p>${escapeHtml(insight.summary)}</p>
    ${stats}
    <h3>3D Knowledge Map</h3>
    <figure>
      <iframe src="${embedOrigin}/embed/map/${insight.id}"
              width="100%" height="520" frameborder="0" allowfullscreen
              style="border:0;border-radius:8px;background:#07080a"></iframe>
      <figcaption>Drag to rotate · scroll to zoom · live from SuperBrain</figcaption>
    </figure>
    <h3>Official claims (excerpt)</h3>
    <ul>${claims}</ul>
    <h3>What's in the full report</h3>
    ${deepStats}
    ${cta}
    <hr>
    <p><em>Generated by SuperBrain · ${insight.generatedAt} · <a href="${embedOrigin}/report/${insight.id}">full cited report</a></em></p>
  `.trim();
}

function escapeHtml(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");
}
